language: node_js
if: branch = master
if: type IN (push)

node_js:
  - 6.0.0

install:
  - npm install --save express
  - npm install --save-dev supertest tape
  - npm install --save-dev tap-spec

script:
  - npm test


before_install:
  - zip -r express-api.zip * -x "./terraform/*" "./scripts/*" .gitignore
  - chmod 700 install_terraform.sh && ./install_terraform.sh
install: chmod 700 deploy_beanstalk.sh && ./deploy_beanstalk.sh
