language: node_js
if: branch = master
if: type IN (push)

node_js:
  - 6.0.0

install:
  - npm install --save express
  - npm install --save-dev supertest tape
  - npm install --save-dev tap-spec

before_install:
  - zip -r express-api.zip * -x "./terraform/*" "./scripts/*" .gitignore
  - chmod -R 700 ./scripts/ && ./scripts/install_terraform.sh
install: ./scripts/deploy_beanstalk.sh
